/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DLL.AccountDLL;
import Entity.NhanVien;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author hieun
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
    }

    AccountDLL accdll = new AccountDLL();

    //close window
    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_DangNhap = new javax.swing.JTextField();
        txt_MatKhau = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_DangNhap = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(74, 31, 61));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LinhStore.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
        );

        jPanel3.setBackground(new java.awt.Color(186, 79, 84));

        txt_DangNhap.setBackground(new java.awt.Color(186, 79, 84));
        txt_DangNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_DangNhap.setForeground(new java.awt.Color(187, 187, 187));
        txt_DangNhap.setToolTipText("");
        txt_DangNhap.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_DangNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_DangNhapKeyPressed(evt);
            }
        });

        txt_MatKhau.setBackground(new java.awt.Color(186, 79, 84));
        txt_MatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_MatKhau.setForeground(new java.awt.Color(187, 187, 187));
        txt_MatKhau.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_MatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_MatKhauKeyPressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Name.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Password.png"))); // NOI18N

        btn_DangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_DangNhap.setText("Đăng nhập");
        btn_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhapActionPerformed(evt);
            }
        });

        btn_Thoat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Thoat.setText("Thoát");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_DangNhap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Thoat)
                        .addGap(47, 47, 47))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txt_DangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_DangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btn_Thoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(74, 31, 61));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SHOP BÁN QUẦN ÁO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhapActionPerformed
        // TODO add your handling code here:
        String user1 = txt_DangNhap.getText();
        String pass1 = String.valueOf(this.txt_MatKhau.getPassword());
        boolean check = true;
        if (check & user1.isEmpty()) {
            check = false;
            JOptionPane.showMessageDialog(this, "Không được để trống!Mời nhập username");
        }
        if (check & pass1.isEmpty()) {
            check = false;
            JOptionPane.showMessageDialog(this, "Không được để trống!Mời nhập password");

        }
        if (check == true) {
            if (accdll.getLogin(user1, pass1).equals("NHÂN VIÊN")) {
                close();               
                
                NhanVien nv = new NhanVien();
                        nv.setTenDangNhap(user1);
                        nv.setMatKhau(pass1);
                Main m = new Main(nv);
               
                
                m.setVisible(true);
            } else if (accdll.getLogin(user1, pass1).equals("QUẢN LÝ")
                    || accdll.getLogin(user1, pass1).equals("CHỦ SHOP")) {
                close();
                NhanVien nv = new NhanVien();
                        nv.setTenDangNhap(user1);
                        nv.setMatKhau(pass1);
                Main m = new Main(nv);
               
      
                m.jButton2.setEnabled(true);
                m.jButton4.setEnabled(true);
                m.jbtn_SuaSP.setEnabled(true);
                m.btn_NhanVien.setEnabled(true);
                m.btn_ThongKe.setEnabled(true);
                m.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Không thể đăng nhập! Kiểm tra lại user và pass");
            }
        }


    }//GEN-LAST:event_btn_DangNhapActionPerformed

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        close();
    }//GEN-LAST:event_btn_ThoatActionPerformed

    private void txt_DangNhapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DangNhapKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String user1 = txt_DangNhap.getText();
            String pass1 = String.valueOf(this.txt_MatKhau.getPassword());
            boolean check = true;
            if (check & user1.isEmpty()) {
                check = false;
                JOptionPane.showMessageDialog(this, "Không được để trống!Mời nhập username");
            }
            if (check & pass1.isEmpty()) {
                check = false;
                JOptionPane.showMessageDialog(this, "Không được để trống!Mời nhập password");

            }
            if (check == true) {
                if (accdll.getLogin(user1, pass1).equals("NHÂN VIÊN")) {
                    close();
                    NhanVien nv = new NhanVien();
                        nv.setTenDangNhap(user1);
                        nv.setMatKhau(pass1);
                Main m = new Main(nv);
               
                    m.setVisible(true);
                } else if (accdll.getLogin(user1, pass1).equals("QUẢN LÝ")
                        || accdll.getLogin(user1, pass1).equals("CHỦ SHOP")) {
                    close();
                    NhanVien nv = new NhanVien();
                        nv.setTenDangNhap(user1);
                        nv.setMatKhau(pass1);
                Main m = new Main(nv);
               
                    m.jButton2.setEnabled(true);
                    m.jButton4.setEnabled(true);
                    m.jbtn_SuaSP.setEnabled(true);
                    m.btn_NhanVien.setEnabled(true);
                    m.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Không thể đăng nhập! Kiểm tra lại user và pass");
                }
            }
        }
    }//GEN-LAST:event_txt_DangNhapKeyPressed

    private void txt_MatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MatKhauKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String user1 = txt_DangNhap.getText();
            String pass1 = String.valueOf(this.txt_MatKhau.getPassword());
            boolean check = true;
            if (check & user1.isEmpty()) {
                check = false;
                JOptionPane.showMessageDialog(this, "Không được để trống!Mời nhập username");
            }
            if (check & pass1.isEmpty()) {
                check = false;
                JOptionPane.showMessageDialog(this, "Không được để trống!Mời nhập password");

            }
            if (check == true) {
                if (accdll.getLogin(user1, pass1).equals("NHÂN VIÊN")) {
                    close();
                    NhanVien nv = new NhanVien();
                        nv.setTenDangNhap(user1);
                        nv.setMatKhau(pass1);
                Main m = new Main(nv);
               
                    m.setVisible(true);
                } else if (accdll.getLogin(user1, pass1).equals("QUẢN LÝ")
                        || accdll.getLogin(user1, pass1).equals("CHỦ SHOP")) {
                    close();
                    NhanVien nv = new NhanVien();
                        nv.setTenDangNhap(user1);
                        nv.setMatKhau(pass1);
                Main m = new Main(nv);
               
                    m.jButton2.setEnabled(true);
                    m.jButton4.setEnabled(true);
                    m.jbtn_SuaSP.setEnabled(true);
                    m.btn_NhanVien.setEnabled(true);
                    m.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Không thể đăng nhập! Kiểm tra lại user và pass");
                }
            }
        }
    }//GEN-LAST:event_txt_MatKhauKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangNhap;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JTextField txt_DangNhap;
    public javax.swing.JPasswordField txt_MatKhau;
    // End of variables declaration//GEN-END:variables
}
